name = "cloudflare-demo-web"
main = ".open-next/worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"

[vars]
NEXT_PUBLIC_API_URL = "https://cloudflare-demo-api.nickycho.workers.dev"
NEXT_PUBLIC_REALTIME_URL = "wss://cloudflare-demo-realtime.nickycho.workers.dev"
