name = "cloudflare-demo-realtime"
main = "src/index.ts"
compatibility_date = "2025-01-01"
account_id = "e2c5f98632ce2f5974707c3b11ef5000"

[[durable_objects.bindings]]
name = "CHAT_ROOM"
class_name = "ChatRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ChatRoom"]
